server:
  port: 8763
spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: 123456

eureka:
  client:
    # 关闭eureka client
#    enabled: false
    # 注册自身到eureka服务器
    register-with-eureka: true
    # 表示是否从eureka服务器获取注册信息
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8763/eureka/

